import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import cookies from "next-cookies";
import Head from "next/head";
import { MdMenu } from "react-icons/md";
import NavBar from "../components/NavBar";
import useNav from "../hooks/useNav";
import Layout from "../layouts/layout";

const Home: NextPage = () => {
  const { navOpen, setNav } = useNav();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>haha</Layout>
    </>
  );
};

export function getServerSideProps(
  ctx: GetServerSidePropsContext
): InferGetServerSidePropsType<any> {
  const cookie = cookies(ctx);

  if (!cookie.firebaseToken) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }

  return {
    props: {},
  };
}

export default Home;
