import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import cookies from "next-cookies";
import Head from "next/head";
import { useAuth } from "../components/UserProvider";
import useCurrentUser from "../hooks/useCurrentUser";

const Home: NextPage = () => {
  const { logOut } = useAuth();
  const currentUser = useCurrentUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen w-screen flex-col items-center justify-center">
        <h1 className="text-3xl font">Hi, {currentUser?.name}</h1>
        <button onClick={logOut} className="btn">
          Log out
        </button>
      </div>
    </>
  );
};

export function getServerSideProps(
  ctx: GetServerSidePropsContext
): InferGetServerSidePropsType<any> {
  const cookie = cookies(ctx);

  if (!cookie.firebaseToken) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }

  return {
    props: {},
  };
}

export default Home;
